sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t svrbedu/dockerreact -f Dockerfile.dev .

script:
  - docker run -e CI=true svrbedu/dockerreact npm run test
